// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofinnqdvdpdbdhxzyndz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9maW5ucWR2ZHBkYmRoeHp5bmR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNDcwNDksImV4cCI6MjA2MTgyMzA0OX0.TIsXJzOX5LbNI1KoP607H6Am6LYOFLTX6hYCgPdHxeQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);